# Generated by Django 2.2 on 2019-04-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='typeof',
            field=models.CharField(blank=True, choices=[('acts', 'Acts'), ('measures', 'Measures'), ('facts', 'Facts')], default='facts', max_length=10),
        ),
    ]
