# Generated by Django 2.2 on 2019-04-27 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20190427_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='health.Article'),
        ),
    ]
