# Generated by Django 2.2 on 2019-04-27 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20190427_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afile', to='health.Article')),
            ],
        ),
    ]
