# Generated by Django 2.2 on 2019-04-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20190427_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlefile',
            old_name='response',
            new_name='article',
        ),
    ]
