# Generated by Django 2.2 on 2019-04-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20190428_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
    ]
