# Generated by Django 2.2 on 2019-04-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_remove_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='answer',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
